import {
  Archive,
  ArrowRight,
  BookOpen,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  Clipboard,
  Code,
  Copy,
  Download,
  Edit,
  Eye,
  File,
  Filter,
  Folder,
  Globe,
  HelpCircle,
  Image,
  Info,
  Key,
  Link,
  List,
  Lock,
  LogIn,
  Mail,
  Menu,
  MessageSquare,
  Monitor,
  Mouse,
  MoveRight,
  Navigation,
  PanelLeft,
  Plus,
  Pointer,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share,
  Sidebar,
  Sliders,
  Star,
  Table,
  Terminal,
  Trash,
  Type,
  Upload,
  User,
  X,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  archive: Archive,
  "arrow-right": ArrowRight,
  book: BookOpen,
  "book-open": BookOpen,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  circle: Circle,
  click: Mouse,
  clipboard: Clipboard,
  code: Code,
  copy: Copy,
  download: Download,
  edit: Edit,
  eye: Eye,
  file: File,
  filter: Filter,
  folder: Folder,
  globe: Globe,
  help: HelpCircle,
  image: Image,
  info: Info,
  key: Key,
  link: Link,
  list: List,
  lock: Lock,
  login: LogIn,
  mail: Mail,
  menu: Menu,
  message: MessageSquare,
  monitor: Monitor,
  mouse: Mouse,
  "move-right": MoveRight,
  navigation: Navigation,
  panel: PanelLeft,
  plus: Plus,
  pointer: Pointer,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share,
  sidebar: Sidebar,
  sliders: Sliders,
  star: Star,
  table: Table,
  terminal: Terminal,
  trash: Trash,
  type: Type,
  upload: Upload,
  user: User,
  x: X,
  zap: Zap,
};

export function getLucideIcon(name: string): LucideIcon {
  if (!name) return Mouse;
  const key = name.toLowerCase().replace(/_/g, "-");
  return iconMap[key] ?? Mouse;
}
