/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Step = IDL.Record({
  'actionLabel' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'uiElement' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreatePlaybookRequest = IDL.Record({
  'title' : IDL.Text,
  'taskGoal' : IDL.Text,
  'steps' : IDL.Vec(Step),
  'screenshot' : ExternalBlob,
  'platformName' : IDL.Text,
});
export const PlaybookId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Playbook = IDL.Record({
  'id' : PlaybookId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'taskGoal' : IDL.Text,
  'steps' : IDL.Vec(Step),
  'screenshot' : ExternalBlob,
  'platformName' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createPlaybook' : IDL.Func([CreatePlaybookRequest], [PlaybookId], []),
  'detectPlatform' : IDL.Func([ExternalBlob], [IDL.Text], []),
  'generatePlaybook' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text],
      [PlaybookId],
      [],
    ),
  'getPlaybook' : IDL.Func([PlaybookId], [IDL.Opt(Playbook)], ['query']),
  'listPlaybooks' : IDL.Func([], [IDL.Vec(Playbook)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Step = IDL.Record({
    'actionLabel' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'uiElement' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreatePlaybookRequest = IDL.Record({
    'title' : IDL.Text,
    'taskGoal' : IDL.Text,
    'steps' : IDL.Vec(Step),
    'screenshot' : ExternalBlob,
    'platformName' : IDL.Text,
  });
  const PlaybookId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Playbook = IDL.Record({
    'id' : PlaybookId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'taskGoal' : IDL.Text,
    'steps' : IDL.Vec(Step),
    'screenshot' : ExternalBlob,
    'platformName' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createPlaybook' : IDL.Func([CreatePlaybookRequest], [PlaybookId], []),
    'detectPlatform' : IDL.Func([ExternalBlob], [IDL.Text], []),
    'generatePlaybook' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text],
        [PlaybookId],
        [],
      ),
    'getPlaybook' : IDL.Func([PlaybookId], [IDL.Opt(Playbook)], ['query']),
    'listPlaybooks' : IDL.Func([], [IDL.Vec(Playbook)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };