/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreatePlaybookRequest {
  'title' : string,
  'taskGoal' : string,
  'steps' : Array<Step>,
  'screenshot' : ExternalBlob,
  'platformName' : string,
}
export type ExternalBlob = Uint8Array;
export interface Playbook {
  'id' : PlaybookId,
  'title' : string,
  'createdAt' : Timestamp,
  'taskGoal' : string,
  'steps' : Array<Step>,
  'screenshot' : ExternalBlob,
  'platformName' : string,
}
export type PlaybookId = bigint;
export interface Step {
  'actionLabel' : string,
  'icon' : string,
  'description' : string,
  'stepNumber' : bigint,
  'uiElement' : [] | [string],
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createPlaybook' : ActorMethod<[CreatePlaybookRequest], PlaybookId>,
  'detectPlatform' : ActorMethod<[ExternalBlob], string>,
  'generatePlaybook' : ActorMethod<[ExternalBlob, string, string], PlaybookId>,
  'getPlaybook' : ActorMethod<[PlaybookId], [] | [Playbook]>,
  'listPlaybooks' : ActorMethod<[], Array<Playbook>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];